### ISSUE TITLE
NoMethodError: undefined method `extension' for nil:NilClass when resolving field

### ISSUE THREAD

**Issue by Mange** [Shopify/graphql-batch#101]
After upgrading to the latest versions of graphql and graphql-batch, the resolvers fail to work when they resolve to a lazy value.

```
› rg graphql Gemfile.lock
154:    graphql (1.9.1)
155:    graphql-batch (0.4.0)
```

Error:

```
NoMethodError: undefined method `extension' for nil:NilClass
graphql-batch-0.4.0/lib/graphql/batch.rb:25:in `block in use'
graphql-batch-0.4.0/lib/graphql/batch.rb:23:in `each'
graphql-batch-0.4.0/lib/graphql/batch.rb:23:in `use'
graphql-1.9.1/lib/graphql/define/defined_object_proxy.rb:28:in `use'
graphql-1.9.1/lib/graphql/schema.rb:781:in `block (2 levels) in to_graphql'
graphql-1.9.1/lib/graphql/schema.rb:777:in `each'
graphql-1.9.1/lib/graphql/schema.rb:777:in `block in to_graphql'
graphql-1.9.1/lib/graphql/define/instance_definable.rb:161:in `instance_eval'
graphql-1.9.1/lib/graphql/define/instance_definable.rb:161:in `ensure_defined'
graphql-1.9.1/lib/graphql/schema.rb:265:in `define'
graphql-1.9.1/lib/graphql/define/instance_definable.rb:130:in `redefine'
graphql-1.9.1/lib/graphql/schema.rb:776:in `to_graphql'
graphql-1.9.1/lib/graphql/schema/member/accepts_definition.rb:120:in `to_graphql'
graphql-1.9.1/lib/graphql/schema.rb:718:in `graphql_definition'
graphql-1.9.1/lib/graphql/schema/field.rb:627:in `with_extensions'
graphql-1.9.1/lib/graphql/schema/field.rb:485:in `resolve'
```

Cause seems to be #99, and this code:
https://github.com/Shopify/graphql-batch/blob/77945d4857f51f05dd36c25d1c599c0cd613a032/lib/graphql/batch.rb#L20-L25

The `metadata` is empty (`{}`) on the field, so it cannot load a value to call `#extension` on. Making the `if` not match, so that part is skipped, makes everything work again.

The type that caused this error is defined using the new class-based syntax, but not all types in the schema is using that syntax. I don't know if it's relevant or not.

This happens both in my test setup (that uses some fixtures and stubs) and with real queries against the schema, so I don't think it's caused by any weird setup on my end.

We do not use the Interpreter and the schema is set up this way:

```ruby
module MyApiName
  class Schema < GraphQL::Schema
    query QueryRoot
    mutation MutationRoot

    use GraphQL::Batch
    use GraphQL::Backtrace
  end
end
```

Moving `use` on top of the other types (which is mentioned as a bad thing in #99) does not change anything either.

Is there anything else I can do here to help debug this? Is there a workaround I can use?

**Comment by rmosolgo** [comment]
> not all types in the schema is using that syntax

Yeah, that's definitely it, if there are types _not_ using the class-based API, then they won't have `.metadata[:type_class]` 😖

**Comment by dylanahsmith** [comment]
Is the MutationRoot defined using the new class-based API?

**Comment by Mange** [comment]
> Is the MutationRoot defined using the new class-based API?

I can confirm that it was using the old style.
