### ISSUE TITLE
Duplicate read of associated records when using AssociationLoader

### ISSUE THREAD

**Issue by bricesanchez** [Shopify/graphql-batch#106]
Hi everyone!

First, i would like to thank you for your awesome job on the OSS community!

I've probably a bug using `graphql-batch`.  I've duplicate reads of `replacements` associated records when i use the `AssociationLoader` class, only after a succeed mutation, not when i use a query. If i disable the batch it works well.

Any idea of what's going bad?

```
data: {,…}
createMandate: {...}
errors: []
mandate: {…}
[...]
replacements: [{id: "144", flexibleTime: false, endsAt: "2019-04-12T01:00:00Z", priority: false,…},…]
0: {id: "144", flexibleTime: false, endsAt: "2019-04-12T01:00:00Z", priority: false,…}
1: {id: "145", flexibleTime: false, endsAt: "2019-04-13T01:00:00Z", priority: false,…}
2: {id: "144", flexibleTime: false, endsAt: "2019-04-12T01:00:00Z", priority: false,…}
3: {id: "145", flexibleTime: false, endsAt: "2019-04-13T01:00:00Z", priority: false,…}
[...]
success: true
``` 

```ruby
# app/models/mandate.rb
class Mandate < ApplicationRecord
  has_many :replacements, class_name: 'Replacement', autosave: true, dependent: :destroy
  has_many :proposals, through: :replacements, class_name: 'Proposal'

  accepts_nested_attributes_for :replacements, allow_destroy: true
end
```

```ruby
# app/graphql/types/mandate.rb
class Types::Mandate < Types::BaseObject
  [..]
  field :replacements, [::Types::Replacement], "Mandate's replacements", null: false
  [..]

  def replacements
    AssociationLoader.for(Mandate, :replacements).load(object)
  end
end
```

```ruby
# app/graphql/association_loader.rb
class AssociationLoader < GraphQL::Batch::Loader
  def self.validate(model, association_name)
    new(model, association_name)
    nil
  end

  def initialize(model, association_name)
    @model = model
    @association_name = association_name
    validate
  end

  def load(record)
    raise TypeError, "#{@model} loader can't load association for #{record.class}" unless record.is_a?(@model)
    return Promise.resolve(read_association(record)) if association_loaded?(record)
    super
  end

  # We want to load the associations on all records, even if they have the same id
  def cache_key(record)
    record.object_id
  end

  def perform(records)
    preload_association(records)
    records.each { |record| fulfill(record, read_association(record)) }
  end

  private

  def validate
    unless @model.reflect_on_association(@association_name)
      raise ArgumentError, "No association #{@association_name} on #{@model}"
    end
  end

  def preload_association(records)
    ::ActiveRecord::Associations::Preloader.new.preload(records, @association_name)
  end

  def read_association(record)
    record.public_send(@association_name)
  end

  def association_loaded?(record)
    record.association(@association_name).loaded?
  end
end
```

**Comment by bricesanchez** [comment]
I've found that if i add a `uniq` in this method, it fix my problem: 

```ruby
# app/graphql/association_loader.rb 
 def perform(records)
    preload_association(records)
    records.each { |record| fulfill(record, read_association(record).uniq) }
  end
```

Not sure if it's the best way to fix the issue

**Comment by palkan** [comment]
Just stumbled across the same problem.

It turned out that `Preloader` doesn't take into account uniqueness of `records` and adds duplicates to the resulting associations ('cause it loads associated records for each passed object).

Solved by adding `uniq` here:

```diff
def perform(records)
-  preload_association(records)
+  preload_association(records.uniq)

end
```

NOTE: we use an upgrade version of `association_loader.rb` compatible with Rails 6: https://gist.github.com/palkan/03eb5306a1a3e8addbe8df97a298a466

**Comment by zhangyonguu** [comment]
> I've found that if i add a `uniq` in this method, it fix my problem:
> 
> ```ruby
> # app/graphql/association_loader.rb 
>   def perform(records)
>     preload_association(records)
>     records.each do |record|
>       read_association_record = read_association(record)
> 
>       if read_association_record.is_a? ActiveRecord::Associations::CollectionProxy
>         read_association_record = read_association_record.distinct
>       end
> 
>       fulfill(record, read_association_record)
>     end
>   end
> ```
> 
> Not sure if it's the best way to fix the issue

anyway, it helped me, thanks!

**Comment by swalkinshaw** [comment]
Could this be related to https://github.com/rails/rails/issues/36396. If so it was fixed in https://github.com/rails/rails/pull/36429

**Comment by zhangyonguu** [comment]
@bricesanchez , 

your method is particularly works when the associations have no order_values, if the associations have order_values and order by expressions not appear in select list, it will raise [this database error](https://stackoverflow.com/questions/12693089/pgerror-select-distinct-order-by-expressions-must-appear-in-select-list):

`ActiveRecord::StatementInvalid: PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list`

so I use the following method to avoid the problem:

```
def perform(records)
    preload_association(records)
    records.each do |record|
      read_association_record = read_association(record)

      if read_association_record.is_a? ActiveRecord::Associations::CollectionProxy && read_association_record.order_values.empty?
        read_association_record = read_association_record.distinct
      end

      fulfill(record, read_association_record)
    end
  end
```

wish the author to fix the problem in essence

**Comment by zhangyonguu** [comment]
@palkan

Suppose A has_many B, and B has_many C

If I have a query:
```
query {
  A{
    B{
      C{
        field
       }
     }
  }
}
```

*records.uniq* can uniq A and B records, but C records still probably duplicated read, so it can not solve the problelm totally.

Luckily the problem seems to solved by the authors.

**Comment by bricesanchez** [comment]
The only way i found to really fix this issue was to update my rails app to 6.0+. Thanks for your help! 😃
