### ISSUE TITLE
[question] Why AssociationLoader needs to overwrite cache_key?

### ISSUE THREAD

**Issue by naku-i386** [Shopify/graphql-batch#108]
Can you explain this to me a little bit more?
```
  # We want to load the associations on all records, even if they have the same id
  def cache_key(record)
    record.object_id
  end
```
Which situation are we talking about here?

**Comment by dylanahsmith** [comment]
As the comment says, it is about two separate records that have the same id.  For example, if you call `SomeModel.find(id)` twice, you would get two different record objects, but they would be considered equal according to their `==` and `to_hash` methods.  However, if you just loaded the association on one of the record objects then accessing the association on the other object would result in a query for data that has already been loaded.
