### ISSUE TITLE
Difficult to integrate graphql-ruby with graphql schema loaded from a `.graphql` file

### ISSUE THREAD

**Issue by myronmarston** [Shopify/graphql-batch#109]
The README shows how to integrate this gem with your project by calling `use` from within a `GraphQL::Schema` subclass:

``` ruby
class MySchema < GraphQL::Schema
  query MyQueryType
  mutation MyMutationType

  use GraphQL::Batch
end
```

However, for our project, we do not have a schema class; instead we are loading our schema at boot time from a `.graphql` file:

``` ruby
schema  = GraphQL::Schema.from_definition(graphql_schema_string, default_resolve: ->(*args) { MyResolver.resolve(*args) })
```

I did some digging through the source code of the `graphql` gem and this gem, and found that I could integrate this gem by doing the following:

``` ruby
GraphQL::Define::DefinedObjectProxy.new(schema).use(GraphQL::Batch)
```

`GraphQL::Define::DefinedObjectProxy` is the only way I could figure out to get this to work, given `GraphQL::Batch#use` [calls `target`](https://github.com/Shopify/graphql-batch/blob/v0.4.0/lib/graphql/batch.rb#L19), which, as afar as I can tell, is only defined on [`GraphQL::Define::DefinedObjectProxy`](https://github.com/rmosolgo/graphql-ruby/blob/v1.9.6/lib/graphql/define/defined_object_proxy.rb#L9).  This works, but took a lot of digging, and it feels like I'm using a private API as I don't think the author of the graphql gem intends `DefinedObjectProxy` to be something that end-users directly instantiate like this.

Am I missing a simpler way to integrate graphql-batch with my project?  Or is there a simple change that could be made to `graphql-batch` to support `GraphQL::Batch.use(schema)` or something similar?

**Comment by swalkinshaw** [comment]
`use` is the official "plugin" API of the graphql gem so I'm not sure this gem should offer anything else. I think the real solution to this would be upstream in graphql itself. Otherwise *every* plugin would have to offer an alternative method. I'd suggest opening an issue there regarding this.

One other thing you could do is just create a simple object which responds to `target` instead of `DefinedObjectProxy`. ie:

```ruby
TargetWrapper = Struct.new(:target)

schema  = GraphQL::Schema.from_definition(graphql_schema_string, default_resolve: ->(*args) { MyResolver.resolve(*args) })
wrapped = TargetWrapper.new(schema)
wrapped.use(GraphQL::Batch)
```

**Comment by myronmarston** [comment]
Thanks!  I'll give that a shot and report this to the graphql gem as well.

**Comment by myronmarston** [comment]
Opened a PR on the graphql gem itself: https://github.com/rmosolgo/graphql-ruby/issues/2307
