### ISSUE TITLE
Release new Gem version to fix class definition syntax?

### ISSUE THREAD

**Issue by TSMMark** [Shopify/graphql-batch#110]
Using the latest graphql gem with latest graphql-batch gem yields errors. https://github.com/Shopify/graphql-batch/issues/101

```
NoMethodError: undefined method `extension' for nil:NilClass
```

0.4.0 is behind master for months since Feb 22, 2019 https://github.com/Shopify/graphql-batch/pull/103

Diff between master and latest release https://github.com/Shopify/graphql-batch/compare/v0.4.0...master?expand=1

Right now we have resorted to pointing ref to latest commit hash on master in our Gemfile, seems to work for now, but are there any plans to release a new gem version like 0.4.1?

**Comment by swalkinshaw** [comment]
v0.4.1 has been released. Sorry for the delay and thanks for the reminder 🎉

**Comment by TSMMark** [comment]
Will try out the new release asap. No apology necessary, thanks for the awesome OSS library!
