### ISSUE TITLE
Loaders that are nested / based on another

### ISSUE THREAD

**Issue by 23tux** [Shopify/graphql-batch#129]
Is it possible to base multiple batch loaders on another? I want to implement a custom `shop_name` for a product, that is based on the city in which the shop is:

```
class Product < ApplicationRecord
  belongs_to :shop
end

class Shop < ApplicationRecord
  has_many :products
  belongs_to :city
end
```

And the GraphQL type would be:

```
# graphql/product_type.rb
field :shop_name, String, null: false

def shop_name
  product = object
  AssociationLoader.for(Product, :shop).load(product).then do |shop|
    AssociationLoader.for(Shop, :city).load(shop).then do |city|
      "#{shop.name} in #{city.name}"
    end
  end
end

```

The outer `AssociationLoader.for(Product, :shop)` is loaded and resolved, but the inner one is never executed. This seems logical, because the async execution of this level of the query already happened, am I right?

Of course, I could just call `shop.city` inside the first `AssociationLoader` but then I would have n+1 queries for multiple products.

Is there any way to achieve this? I first thought using a `Promise.all` could help, but the promises wouldn't know anything from another, so you can't use the result from the first promise to build the second promise.

**Comment by dylanahsmith** [comment]
I'm not able to reproduce this problem.  Why do you say "the inner one is never executed"?  What is the result that you are seeing?  The `then` block should be called unless the promise resolves to an error.

**Comment by 23tux** [comment]
@dylanahsmith sorry for the long wait! I tested it again, and you were right, it works! Seems like something was wrong on my side.
