### ISSUE TITLE
How to Implement Pagination with AssociationLoader using Connections?

### ISSUE THREAD

**Issue by toyhammered** [Shopify/graphql-batch#130]
I was wondering if it is possible to implement an AssociationLoader which includes pagination using connections. I am using the exact example provided [in the documentation](https://github.com/Shopify/graphql-batch/blob/master/examples/association_loader.rb).

With the current setup below it will be making 2 database calls. The first would be a `Select * From Posts` (AssociationLoader will return this) while the second will be done through the connection (what is passed into the nodes from the field value) which would run `Select * From Posts Limit (2)`. This is obviously inefficient. Is there a way actually paginate using the AssociationLoader? What would the recommend approach/best practice be?

```
class SomeSchema < GraphQL::Schema
  default_max_page_size 2
end
```
```
class Types::User < Types::BaseObject
  field :id, ID, null: false

  field :posts, Types::Post.connection_type, null: false

  def posts
    AssociationLoader.for(object.class, :posts).load(object)
  end
end
```

**Comment by dylanahsmith** [comment]
This seems like a duplicate of https://github.com/Shopify/graphql-batch/issues/114 .  I think you have to start by figuring out what you even want the SQL to be based on what is efficient for your datastore.

> If you're on a sufficiently recent version of MySQL/Postgres/whatever you can use window functions, roughly similar to the explanation at https://www.the-art-of-web.com/sql/partition-over/.

**Comment by toyhammered** [comment]
Thank you for linking existing issue!
