### ISSUE TITLE
Promises fail to be resolved for Relay connection_type

### ISSUE THREAD

**Issue by joshjcarrier** [Shopify/graphql-batch#26]
[Relay support in graphql-ruby](https://rmosolgo.github.io/graphql-ruby/relay/connections) suggests resolvers for a `connection_type` should be able to return an array. Expect that `graphql-batch` would support field resolver returning promise of an array in this scenario. It instead fails with exception `No connection implementation to wrap GraphQL::Batch::Promise`.

A workaround is to have the resolver wait for promise fulfillment by calling [Promise#sync](https://github.com/lgierth/promise.rb/blob/master/lib/promise.rb#L63) on the `Loader#load/#load_many` result. 

@cjoudrey @dylanahsmith

For a repro, consider this script using `graphql (0.19.4)` and `graphql-batch (0.2.4)` on `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]`:

``` ruby
require 'graphql/batch'

class ShopLoader < GraphQL::Batch::Loader
  def initialize(ctx)
  end

  def perform(ids)
    ids.each { |id| fulfill(id, OpenStruct.new({ id: id })) }
  end
end

class ShopResolver
  def self.call(obj, args, ctx)
    ShopLoader.for("ctx").load_many([ 1, 2, 3 ])
  end
end

ShopType = GraphQL::ObjectType.define do
  name "Shop"

  field :id do
    type types.ID
  end
end

QueryType = GraphQL::ObjectType.define do
  name "Query"

  field :shops do
    type types[ShopType]
    resolve ShopResolver
  end

  connection :shopsConnection, ShopType.connection_type do
    resolve ShopResolver
  end
end

Schema = GraphQL::Schema.define do
  query QueryType
end

Schema.query_execution_strategy = GraphQL::Batch::ExecutionStrategy
Schema.mutation_execution_strategy = GraphQL::Batch::MutationExecutionStrategy

puts "Array use of cache loader:"
puts Schema.execute("{ shops { id } }")
# {"data"=>{"shops"=>[{"id"=>"1"}, {"id"=>"2"}, {"id"=>"3"}]}}

puts "Connection use of cache loader:"
puts Schema.execute("{ shopsConnection { edges { node { id } } } }")
# /Users/jocarrie/.rvm/gems/ruby-2.3.0/gems/graphql-0.19.4/lib/graphql/relay/base_connection.rb:37:in `connection_for_nodes': 
# No connection implementation to wrap GraphQL::Batch::Promise (#<GraphQL::Batch::Promise:0x007f8081152170>) (RuntimeError)
#   from /Users/jocarrie/.rvm/gems/ruby-2.3.0/gems/graphql-0.19.4/lib/graphql/relay/connection_resolve.rb:12:in `call'
```

**Comment by dylanahsmith** [comment]
Now that graphql-relay-ruby has been merged into graphql-ruby, we could probably be clearer about the fact that the relay code in graphql-ruby isn't supported by graphql-batch.

We mention in the README that

> The loader class can be used from the resolve proc for a graphql field

and in this case you are trying to use the loader in a connection resolve proc, not on the field resolve proc.

You may be able to support this by using GraphQL::Relay::BaseConnection.register_connection_implementation.

**Comment by joshjcarrier** [comment]
Here's the simplest thing I could do convert over:

```ruby
module GraphQL
  module Batch
    class SyncPromiseConnection < GraphQL::Relay::ArrayConnection
      private

      def nodes
        super.sync
      end
    end
  end
end

GraphQL::Relay::BaseConnection.register_connection_implementation(GraphQL::Batch::Promise, GraphQL::Batch::SyncPromiseConnection)
```

At least it lets this gem work by default with connections? Is it worth further investment?

**Comment by dylanahsmith** [comment]
Calling sync like that would prevent batching.

With graphql-ruby's new [lazy execution API](https://github.com/rmosolgo/graphql-ruby/blob/master/guides/schema/lazy_execution.md) it will actually be possible to fix this upstream, so I'm going to consider this an upstream issue now and close the issue here.

**Comment by rmosolgo** [comment]
Upstream fix here! 

https://github.com/rmosolgo/graphql-ruby/pull/425

**Comment by mengqing** [comment]
Is there an example on how to implement this? Using the association loader in the example folder would produce N+1 on connection types
