### ISSUE TITLE
Loader cache is short lived

### ISSUE THREAD

**Issue by farnoy** [Shopify/graphql-batch#43]
Hi, for a query like this:

```graphql
query {
  company(id: 10) {
    job {
      company {
        id
      }
    }
}
```

I checked that (with my loaders) it will do 3 queries. First to fetch the Company, then Job, then Company again. The last query is cached by ActiveRecord, so it's not a big deal. I am wondering if it should be cached in graphql-batch instead. Both the top level `company` field and `company` under `Job` type are essentially resolved like this: `RecordLoader.for(Company).load(10)` but the caches seem to live until all direct children and siblings are resolved. In other words, the cache is effectively purged by the time my nested `company` field is being resolved.

Is there a reason why we couldn't cache these loaders for longer periods of time?

**Comment by dylanahsmith** [comment]
Yes, it should cache for the whole query.  I have made steps in this direction, but it is still a remaining issue.

Right now it only does batching, but no caching.  So it will do denormalization for the same of a given batch query, but it will not cache for further batch queries.  This usually comes up when the same query is needed at multiple levels in the query.

**Comment by dylanahsmith** [comment]
Should be fixed by https://github.com/Shopify/graphql-batch/pull/53 now

**Comment by dylanahsmith** [comment]
Reopening this because #53 was reverted due to it resulting in loader re-use across mutation fields
