### ISSUE TITLE
Batch::Loader and Context

### ISSUE THREAD

**Issue by BjRo** [Shopify/graphql-batch#46]
I wasn't able to figure that out from the documentation (and quick glances in the code), could you please clarify a bit here?

How does `GraphQL::Batch::Loader` interplay with `graphql-ruby's`  resolve context. I don't see any way of accessing it in the `GraphQL::Batch::Loader`. 

Is that intentional because you would loose the ast node context when batching? If the context is not accessible, what's the suggested way of dealing with context data (like the current user_id or something comparable)?

**Comment by dylanahsmith** [comment]
What do you need from the context?  If it is something that affects the query being performed, then pass it in either to `.for` or `.load` depending on how it affects how the queries can be batched.

E.g.

```ruby
CountLoader.for(User, :friends).load(context[:user_id])
```

There are no plans to add more coupling with `graphql-ruby` and I think it would be a mis-feature to implicitly make more information available to the loader that isn't explicitly used for grouping or a key for what to load.
