### ISSUE TITLE
Release master?

### ISSUE THREAD

**Issue by rmosolgo** [Shopify/graphql-batch#62]
Hi, would you mind releasing master to rubygems? 0.3.3 has the caching patch which was removed on master. Master is testing a bit better for but it's easier for our CI to point at rubygems. Could you cut a new version?

**Comment by dylanahsmith** [comment]
Pushed a 0.3.4 version release with the bug fixes.  As you noted, there is a revert in there that could cause a performance regression from not caching loaders after they are resolved, but that was needed to fix a correctness bug to avoid batching across mutation fields.

**Comment by rmosolgo** [comment]
Thanks, it's working great :)
