### ISSUE TITLE
Is there a way to add errors to the query context from within `RecordLoader#perform`?

### ISSUE THREAD

**Issue by Mori** [Shopify/graphql-batch#71]
After executing a `perform` to resolve the promises into records, I'd like to be able to add  "Record not found" errors for unfound ids to the graphql-ruby error array. However, I don't see a way to do that from with in `RecordLoader#perform`, or after. Is there a way to access the query context from this method? Or any other mechanism for this? 

Thanks ...

**Comment by dylanahsmith** [comment]
Why can't you just raise an exception? That will reject the promises the loader hasn't fulfilled, which could be handled by the field or the result of the field being a rejected promise would be the same as if that exception were raised in the field resolver.

**Comment by Mori** [comment]
@dylanahsmith, thank you for the suggestion. I went ahead and tried this in `RecordLoader#perform`:

    fail GraphQL::ExecutionError, fail_message

This causes a `NameError` in version 0.3.7, but not in 0.3.8. But even in 0.3.8, it doesn't get trapped in the rescue block of any field resolver.

**Comment by dylanahsmith** [comment]
The test suite has [test_load_error](https://github.com/Shopify/graphql-batch/blob/v0.3.8/test/graphql_test.rb#L312) which tests a [field returning a promise that gets rejected](https://github.com/Shopify/graphql-batch/blob/v0.3.8/test/support/schema.rb#L79)..

There is also [test_loader_with_failing_perform](https://github.com/Shopify/graphql-batch/blob/v0.3.8/test/loader_test.rb#L172) which tests a loader that raises an exception in its perform method.

So I'm not sure why it isn't behaving properly.  Could you provide a failing test or simple script that reproduces the problem?

**Comment by Mori** [comment]
Looking at those test examples I see that I should have been raising any errors in a `then` clause rather than in `RecordLoader#perform`. That way errors can be allocated to the correct individual fields. E.g.

     loader(@type) 
       .for(Graph::ResolveType.type_to_model(@type, ctx)) 
       .load(Graph::ObjectId.uuid_to_oid(args[:id])) 
       .then { |object| 
         if object 
           object 
         else 
           fail GraphQL::ExecutionError, "#{ctx.type.name} #{args[:id]} not found" 
         end
       } 

It's now working as expected. Thanks @dylanahsmith.
