### ISSUE TITLE
Ask for Sequel users

### ISSUE THREAD

**Issue by razertory** [Shopify/graphql-batch#82]
Could there be a [Sequel](https://github.com/jeremyevans/sequel) `association_loader.rb` example , just like the Active Record one?

**Comment by dylanahsmith** [comment]
We don't plan on writing an example for Sequel.  Is that what you are offering?

How different would it be from the current association_loader.rb?  Wouldn't it just be replacing the last three methods https://github.com/Shopify/graphql-batch/blob/4ae285e4c2b873a5338ae555abeb5bc58647ec46/examples/association_loader.rb#L37-L47 with something non-active record specific?

**Comment by razertory** [comment]
Sequel's association_loader example is just here and thanks to @rmosolgo , his example woks.
```ruby
class ForeignKeyLoader < GraphQL::Batch::Loader
  def initialize(model, foreign_key)
    @model = model
    @foreign_key = foreign_key
  end

  def perform(foreign_value_sets)
    foreign_values = foreign_value_sets.flatten.uniq
    records = @model.where(@foreign_key => foreign_values).to_a

    foreign_value_sets.each do |foreign_value_set|
      matching_records = records.select { |r| foreign_value_set.include?(r.send(@foreign_key)) }
      fulfill(foreign_value_set, matching_records)
    end
  end
end
```

**Comment by dylanahsmith** [comment]
That isn't loading Sequel's associations.

I could see that a ForeignKeyLoader might be the next best thing and could be implemented in a way that works with active record and Sequel.

**Comment by dylanahsmith** [comment]
It looks like the RecordLoader can already act as a foreign key loader for a `has_one` association (e.g. `RecordLoader.for(ProductImage, column: :product_id).load(product_id)`).  It just needs to be extended to allow multiple records by a foreign key.  This could be done by adding a `unique: false` parameter.

Thoughts on changing the RecordLoader example as shown in this [foreign-key-loader-example branch](https://github.com/Shopify/graphql-batch/compare/foreign-key-loader-example)?

Likely the column type casting would still need to be removed to work with Sequel.

**Comment by ayrton** [comment]
@jeremyevans any pointers as to how the `AssociationLoader` would look like for Sequel?

**Comment by jeremyevans** [comment]
Unfortunately, I do not have the time to research the code and come up with a tested example.  In terms of the first example:

```ruby
 # No direct equivalent to this in Sequel, but if you use the
 # tactical_eager_loading plugin, records will be preloaded
 # automatically as a set when needed.  Assuming you use
 # that plugin, this could be empty. 
 def preload_association(records) 
 end 
  
 # This works, but returns an array in Sequel, not a proxy object
 def read_association(record) 
   record.public_send(@association_name) 
 end 
  
 def association_loaded?(record) 
   record.associations.has_key?(@association_name) 
 end 
```

**Comment by f16z** [comment]
Just what I needed.
