### ISSUE TITLE
Define custom loader in a block

### ISSUE THREAD

**Issue by mengqing** [Shopify/graphql-batch#85]
How would I go about define a custom loader within the GraphQL field definition, instead of creating a loader class?

**Comment by mengqing** [comment]
Thanks for the advice @dylanahsmith, it works perfectly for me, after fulfilling keys that don't have a result

```
def perform(keys)
  @block.call(keys, self)
  keys.each { |id| fulfill(id, nil) unless fulfilled?(id) }
end
```

**Comment by dylanahsmith** [comment]
I don't think `nil` is always an appropriate default though.  In some cases an array would be a more appropriate default.  Perhaps a keyword argument could be provided to control that default.  E.g. `BlockLoader.for(default: nil) do |keys, result|`
