### ISSUE TITLE
optimize question 

### ISSUE THREAD

**Issue by razertory** [Shopify/graphql-batch#86]
In `graphql-ruby`,  I've found that every single field of a type is not asynchronizly resolved
```ruby
# the sleep method represents any blocking method call or IO
field :a, types.String do 
    resolve -> (o, args, c) {
      sleep 3
      "a"
    }
  end

  field :b, types.String do 
    resolve -> (o, args, c) {
      sleep 3 
      "b"
    }
  end

  field :c, types.String do 
    resolve -> (o, args, c) {
      sleep 3 
      "c"
    }
  end

  field :d, types.String do 
    resolve -> (o, args, c) {
      sleep 3 
      "d"
    }
  end

```
if a query like 
```graphql
test {
    a
    b
    c
    d
  }
```
the time cost could be 
```shell
Completed 200 OK in 12602ms (Views: 0.6ms)
```
seems like the time cost is 3 * 4 = 12 second
I want to get the field concurrently, then the time cost could be nearly 3 second. Is it a good way to use your gem ? Or I should submit a new issue in [graphql-ruby](https://github.com/rmosolgo/graphql-ruby) 😂

**Comment by dylanahsmith** [comment]
graphql-ruby support [Lazy Execution](http://graphql-ruby.org/schema/lazy_execution.html) which sounds like what you want.  If you don't need batching, then I would just use that directly.  That Lazy Execution feature was an extraction from this gem and thus is used by this gem.

If you decide to use this gem for batching but want to load the batch queries concurrently, then https://github.com/Shopify/graphql-batch/issues/45 is the relevant issue.
