### ISSUE TITLE
KeyError (key not found: 1)

### ISSUE THREAD

**Issue by NicholasLYang** [Shopify/graphql-batch#87]
Hi, I'm getting the following error with my code:

```
KeyError (key not found: 1):
  
app/graphql/loaders/record_loader.rb:9:in `block in perform'
app/graphql/loaders/record_loader.rb:9:in `perform'
app/controllers/graphql_controller.rb:10:in `execute'
```
I can't quite figure out what I'm doing wrong, since the code is pretty much copied from the docs.
record_loader.rb:

```
require 'graphql/batch'

class Loaders::RecordLoader < GraphQL::Batch::Loader
  def initialize(model)
    @model = model
  end

  def perform(ids)
    @model.where(id: ids).each { |record| fulfill(record.id, record) }
    ids.each { |id| fulfill(id, nil) unless fulfilled?(id) }
  end
end
```
and my query resolver:
```
  field :schoolById, Types::SchoolType do
    description "Get school by id"
    argument :id, types.ID
    resolve -> (obj, args, context) {
      Loaders::RecordLoader.for(School).load_many(args["id"])
    }
  end
```
I've double checked my code, and `args["id"]` is a single element, not an array, so #50 isn't the issue. Guessing by the error message, the issue is in fulfill, but I'm not sure how or why. It's probably something small or dumb that I'm missing haha.

Thanks for your time,
Nicholas

**Comment by dylanahsmith** [comment]
Are you passing a string id value for an integer column? [examples/record_loader.rb](https://github.com/Shopify/graphql-batch/blob/master/examples/record_loader.rb) uses casting to avoid that problem

**Comment by NicholasLYang** [comment]
Ah yes, that makes sense. Thanks!
