### ISSUE TITLE
[Question] Objects, structs or hashes as loader key

### ISSUE THREAD

**Issue by naku-i386** [Shopify/graphql-batch#92]
Hello,

Is it okay to use a struct, hash or object as loader key?
```
Loader.for(Product, key: :id).load(obj) # pass whole object to loader
```
At first it does not sound like a good idea. I want the object to be available inside the loader and perform authorization there. Sometimes you need to query for another resource during authorization and to avoid N+1 it has to happen inside the loader. I can provide more details about the issue but the answer would be appreciated :+1: 

Perhaps something like this would be pretty useful.
```
Loader.for(Product).load(obj.id, obj) # optionally pass object
```

**Comment by naku-i386** [comment]
Great! Thank you for your response. I created a prototype of my authorization, used objects as keys and it WORKS but i actually pass the context to loader `::for`. **What are possible drawbacks of grouping by context - broken query cache?** 

Your idea of overriding key methods sounds like something i should be going for so i will try implementing it that way.

My goal was to create some standard in our app for authorization. Often it's simple `==` check but sometimes you need to query for more information. So to avoid confusion i thought it would be good idea to do something similar to:

```
Loader.for(Product, { Guard::Team => :members }, { :id => :team_id }).load(obj)
```

**Comment by dylanahsmith** [comment]
I think the graphql gem creates a context for each object, so I think grouping by the context would prevent it from grouping together loads for multiple objects.  If so, then the batch loader would be quite useless because it wouldn't be actually batch loading.

**Comment by naku-i386** [comment]
Thank you. That's sufficient explanation.
