### ISSUE TITLE
[Question] How to working with resolver ?

### ISSUE THREAD

**Issue by jasl** [Shopify/graphql-batch#98]
I'm trying to use this with a resolver class, e.g:

```ruby
class EntityResolver < GraphQL::Schema::Resolver
  argument :id, ::GraphQL::Types::ID, required: true

  def resolve(id:)
    ::Loaders::RecordLoader.for(Entity).load(id)
  end
end
```

In my Schema

```ruby
field "entity", EntityType, null: false, resolver: EntityResolver
```

And do query, then I got 

```
`GraphQL::Batch::NoExecutorError - Cannot create loader without an Executor.
Wrap the call to `for` with `GraphQL::Batch.batch` 
or use `GraphQL::Batch::Setup` as a query instrumenter if using with `graphql-ruby`
```

I've tried `GraphQL::Batch.batch { ::Loaders::RecordLoader.for(Entity).load(id) }` but got GQL's null error message.

How to working with resolver?

**Comment by thetizzo** [comment]
Hi 👋 

Do you need the resolver class?  I'm wondering if you can just call the loader using a proc in the schema like this:

```ruby
field "entity", EntityType, null: false, 
  resolve: -> (obj, args, context) { Loaders::RecordLoader.for(Entity).load(args["id"]) }
```
This implementation has worked for me in a couple of places and since the [GQL docs](https://graphql-ruby.org/fields/resolvers.html#first-ask-yourself-) seem to recommend against using a Resolver class, I think using the proc might be simpler and preferable.

**Comment by jasl** [comment]
> Hi 👋
> 
> Do you need the resolver class? I'm wondering if you can just call the loader using a proc in the schema like this:
> 
> ```ruby
> field "entity", EntityType, null: false, 
>   resolve: -> (obj, args, context) { Loaders::RecordLoader.for(Entity).load(args["id"]) }
> ```
> 
> This implementation has worked for me in a couple of places and since the [GQL docs](https://graphql-ruby.org/fields/resolvers.html#first-ask-yourself-) seem to recommend against using a Resolver class, I think using the proc might be simpler and preferable.

I read the doc, but unfortunately I really need Resolvers

**Comment by sunhohong** [comment]
Did you add this code to your schema?
```
use GraphQL::Batch
```

**Comment by jasl** [comment]
@sunhohong just do a re-test, the problem solved, only different is I did a `bundle update` few days ago.

**Comment by SanskarSans** [comment]
`RecordLoader.for(Entity).load(ids)`
I see ids is used as an argument but what if I want to fetch all the records of Entity.
